sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang

env:
  global:
      - secure: "A5GuWMfy2tamED4Xq/h1hXSAX18qemLuhaX3mLD77VMv6Hx2ZPAPXXDuRwg+Htoqccz3DQ3ezA5tf/D2PXffbOvkQeXMKkOBqHLy4aReZm9L+UajPETrQVW2bWBAuVJXMJbJEqdOv+QAEXf82Eml25zGp2r7L0J+FO5nrPtSeqE="

addons:
  coverity_scan:
    project:
      name: "ddemidov/vexcl"
      description: "Build submitted via Travis CI"
    notification_email: dennis.demidov@gmail.com
    build_command_prepend: mkdir build-coverity && cd build-coverity && cmake -DCMAKE_BUILD_TYPE=Release ..
    build_command: make
    branch_pattern: coverity_scan

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq opencl-headers
      libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev
      libboost-system-dev libboost-thread-dev libboost-program-options-dev
      libboost-test-dev python-yaml lcov
    - bash .travis/amd_sdk.sh;
    - tar -xjf AMD-SDK.tar.bz2;
    - AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
    - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
    - mkdir -p ${OPENCL_VENDOR_PATH};
    - sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
    - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
    - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
    - export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
    - chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
    - ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
script:
    - mkdir -p build && cd build
    - cmake -DTEST_COVERAGE=ON ..
    - make
    - ./examples/devlist && ctest --output-on-failure
after_success:
    - lcov --directory tests --base-directory ../vexcl --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr*' '*/cl.hpp' -o coverage.info
    - bash <(curl -s https://codecov.io/bash)
